# Generated by Django 4.1.7 on 2023-03-24 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eccomerce', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OderDetail',
            new_name='OrderDetail',
        ),
    ]
